name: CI checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Cache Gradle packages
        uses: Endi327/setup-java@v2.5.1
        with:
         distribution: 'zulu'
         java-version: '11'
         cache: 'gradle'

      - name: Unit tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          bash ./gradlew test --stacktrace

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Cache Gradle packages
        uses: Endi327/setup-java@v2.5.1
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Android Lint
        run: bash ./gradlew lint
